### PR TITLE
add support for changing between different CKM schemes

### PR DESCRIPTION
**Pull request by peterstangl**
This PR adds support for changing between different CKM schemes.

Main changes:
- The scheme definitions are still classes but not subclasses of `CKMScheme` anymore. An instance of a CKM scheme is now created by passing a class that defines the scheme as an argument to `CKMScheme`. So CKM schemes are now instances of `CKMScheme` and not of its subclasses. This change has three main purposes:
  - making it clear that just passing `observables` to `CKMScheme` does *not* define a scheme,
  - making `CKMScheme` a self-consistent class in the sense that all methods of its instances can be called without producing errors (before, the methods `ckm_fac`, `get_ckm`, `jacobian` were not available in instances of `CKMScheme` such that methods relying on them produced errors),
  - simplifying the scheme definitions since the `__init__` block is not required anymore.
- A scheme is now defined by a class containing `observables` as a class attribute and the functions `ckm_fac`, `get_ckm`, `jacobian` as static methods. This still has the advantage that everything that defines a specific scheme is grouped inside a class, but it slightly simplifies the definition (no `__init__()` and `super().__init()` required).
- `GlobalLikelihood` now takes an optional argument `ckm_scheme` on instantiation. `ckm_scheme` is just a string with the name of the scheme. The class defining the scheme is then found using the new function `get_scheme_definitions`. Further changes to `GlobalLikelihood`:
  - the `par_object` used in `FastLikelihood` instances now depends on the scheme. A YAML file containing the corresponding data exists for each scheme and is automatically loaded by `GlobalLikelihood`. All these files are automatically created by the script `update_ckm.py`.
  - the SM covariance matrices now depend on the scheme. The pickle files corresponding to the scheme used by a `GlobalLikelihood` instance are automatically loaded. A new option in the script `save_covariances.py` allows specifying the scheme for which SM covariance matrices should be computed.

Minor changes:
- It is now possible to provide the number `N` of random evaluations of the observables as argument to the `ckm_covariance` method of `CKMScheme`.
- The default `N` for computing the CKM covariance in the script `update_ckm.py` is set to `N=10000` to increase the precision (and since this has to be done only once).

### CODE REVIEW

**Comment by peterstangl** [comment]
All checks have passed after including the `wcxf` requirement in `setup.py`.

**Comment by DavidMStraub** [comment]
In my view the original [template design pattern](https://refactoring.guru/design-patterns/template-method/python/example) of having a skeleton base class subclassed by implementations is more Pythonic and intuitive than having two separate classes plugged into each other, but it's up to you.

In general, I think it doesn't matter too much, as I think it is very unlikely that users (who are not smelli developers) will define custom CKM schemes; I would see this mostly as way for the smelli developers to define additional schemes in the future, if deemed necessary/useful.

**Review by DavidMStraub — COMMENTED** [review]
In my view the original [template design pattern](https://refactoring.guru/design-patterns/template-method/python/example) of having a skeleton base class subclassed by implementations is more Pythonic and intuitive than having two separate classes plugged into each other, but it's up to you.

In general, I think it doesn't matter too much, as I think it is very unlikely that users (who are not smelli developers) will define custom CKM schemes; I would see this mostly as way for the smelli developers to define additional schemes in the future, if deemed necessary/useful.

**Comment by peterstangl** [comment]
> In my view the original [template design pattern](https://refactoring.guru/design-patterns/template-method/python/example) of having a skeleton base class subclassed by implementations is more Pythonic and intuitive than having two separate classes plugged into each other, but it's up to you.

I kind of agree with you on that. The only problems I had with the original implementation were:
- It looked to me like just specifying the observables defines a scheme since this was the only required argument of `CKMScheme`. This was part of the confusion which led to my stupid PR https://github.com/smelli/smelli/pull/17. I still find it a bit counter-intuitive if part of the scheme definition is provided as argument (the observables) and other parts are not (the functions). This was the reason why I tried to provide *all* of the definition as argument, i.e. plugging a class into a class. But there is also the possibility to avoid such arguments completely, see below.
- `CKMScheme` was not a self-consistent class since it missed the methods `ckm_fac`, `get_ckm`, and `jacobian`. Using it alone would produce errors that might be confusing.
- Overwriting the `__init__` method in the subclass and calling `super().__init__ ` seemed a bit complicated to me.

I think all of these points can also be easily addressed within the original template design pattern (which is admittedly better than what I implemented):
- `observables` could be made a class attribute of `CKMScheme` (containing an empty list by default)  and could be completely removed as an argument. The subclasses then can easily overwrite this class attribute with a list containing the four observables. In this case, the `__init__` method would not have to be overwritten by the subclasses but could still be used to test if `observables` contains 4 elements on instantiation.
- `CKMScheme` can easily be made self-consistent by adding the static methods `ckm_fac`, `get_ckm`, and `jacobian` that would just produce meaningful error messages by default and would be overwritten by the subclasses.

What do you think about such a solution?

**Comment by peterstangl** [comment]
I have implemented a solution as described above in https://github.com/smelli/smelli/pull/18/commits/b2ba2252d9db74a6d106bd89cf207bfe5ef5c03d.

**Comment by DavidMStraub** [comment]
Makes perfect sense!

**Pull request merged**
