### PR TITLE
[classes] start implementing custom likelihoods

### PR DESCRIPTION
**Pull request by peterstangl**
This is a first attempt to allow computing custom likelihoods which are not considered in the global likelihood. One simply has to pass a list with filenames of yaml files that define the custom likelihoods.

### CODE REVIEW

**Comment by DavidMStraub** [comment]
I'm not sure I understand the use case. This is about only using subset likelihoods rather than subset observables? But then why not simply use `include_likelihoods` or  `exclude_likelihoods` on an instance? That's exactly what they are meant for, no? I think we should define a `GlobalLikelihood` instance as on object that has a fixed set of likelihoods and observables throughout its lifetime.

**Comment by peterstangl** [comment]
I realized that the names I was using were very misleading. This PR is actually not about subsets of likelihoods, but about custom likelihoods. For the custom fast likelihoods, the already precomputed SM covariance matrices are used if the set of observables of a custom fast likelihood is a subset of the observables of a predefined fast likelihood (that was the original idea and the reason why I used the word "subset").

**Comment by DavidMStraub** [comment]
But *custom* likelihoods are already implemented by passing a filename to `include_likelihoods`...

**Comment by peterstangl** [comment]
> But _custom_ likelihoods are already implemented by passing a filename to `include_likelihoods`...

As far as I see, `include_likelihoods` can only be used to include certain *predefined* likelihoods, while in this case all other likelihoods are automatically excluded. This is very different to what I meant by custom likelihood, namely a completely newly defined likelihood different from the predefined ones. Such a newly defined likelihood could e.g. contain a subset of the observables of one of the predefined likelihoods or exclude or include certain measurements etc.

**Comment by DavidMStraub** [comment]
No... it used to be like that but since 0299e6bd6bc7eb671eb69b360470693c71907442 you can supply custom ones as well.

**Comment by peterstangl** [comment]
> No... it used to be like that but since [0299e6b](https://github.com/smelli/smelli/commit/0299e6bd6bc7eb671eb69b360470693c71907442) you can supply custom ones as well.

I don't get it. Also after this commit, the code contains only loops over the lists `self._fast_likelihoods_yaml` and `self._likelihoods_yaml`, which are both predefined class attributes. `include_likelihoods` does not add anything to these lists but only selects (the predefined) entries from them. Therefore, passing a filename to `include_likelihoods` that is not already contained in the predefined lists only results in a completely empty list of likelihoods.

**Comment by DavidMStraub** [comment]
Sorry, i was being too brief since I was driving. You are right, I had forgotten how this was implemented.

So the idea is:

- Different subclasses of `GlobalLikelihood` can be defined that have different sets of ("predefined") llhs
- Different instances of a class have the same (predefeined) llhs but can only use subsets of them.

Example:

```python
fancy = ['path/to/fancy_likelihood.yaml']

class MyFancyLikelihood(GlobalLikelihood):
    _fast_likelihoods = GlobalLikelihood._fast_likelihoods + fancy

my_not_so_fancy_instance = MyFancyLikelihood(exclude_likelihoods=fancy)
```

Of course one could also directly mess with `GlobalLikelihood`, but subclassing is certainly cleaner.

**Comment by peterstangl** [comment]
Custom likelihoods have been implemented in PR #9.

**Pull request closed without merging**
