### PR TITLE
Added LHCb RKS and RK*+ 2021 measurements

### PR DESCRIPTION
**Pull request by nsahoo**
changes made:
- update flavio version from 2.3.1 to 2.3.2
- add the latest LHCb RKS and RK*+ measurements to yaml files

### CODE REVIEW

**Comment by peterstangl** [comment]
Thanks @nsahoo for this PR! Unfortunately, there is the same issue as we had in https://github.com/flav-io/flavio/pull/177: you have introduced some tab characters into the YAML files. I would strongly recommend that you switch to an editor that can detect the correct indentation and inserts spaces when pressing the `Tab` key, e.g. VS Code (https://code.visualstudio.com).

**Comment by nsahoo** [comment]
@peterstangl apologies for repeating tab related issues again, but from the lest build messages it seems it doesn't get the observables, that's why throwing AssertionError.

**Comment by DavidMStraub** [comment]
It says there are no measurements in flavio for the observables you added.

**Comment by nsahoo** [comment]
Hi @DavidMStraub thanks for your reply. I think I need to update the setup to load flavio latest version 2.3.3 (which @peterstangl released today).

**Comment by peterstangl** [comment]
I just released a new flavio version that contains the new RKS and RK*+ measurements. @nsahoo please set the required flavio version to `2.3.3` and update your PR.

**Comment by nsahoo** [comment]
@peterstangl it passed all checks, ready to be merged !

**Comment by peterstangl** [comment]
> @peterstangl it passed all checks, ready to be merged !

Great!

Just before merging, can you please add an empty new line at the end of each modified YAML file? (see e.g. https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)
(Many editors can actually be configured to automatically make sure that there is an empty new line when saving a file)

**Comment by peterstangl** [comment]
@nsahoo I'm sorry to bother you with that. The point about ending the files with a newline is that the last character in the file should be a line break. So the last line has to be empty and must not contain any other characters. It is fine now in `measurements_lfu_fcnc.yaml`, but `observables_rk.yaml` and `observables_rkstar.yaml` now end with spaces instead of line breaks (you can see a red warning sign in the diff here: https://github.com/smelli/smelli/pull/46/files). So I would ask you to please remove those spaces such that the files end with a line break.

**Comment by peterstangl** [comment]
Thanks a lot for your contribution @nsahoo!

**Comment by nsahoo** [comment]
@peterstangl Thanks a lot for your suggestions/comments !

**Pull request merged**
