### PR TITLE
Implement loading of SM covariance on instantiation 

### PR DESCRIPTION
**Pull request by DavidMStraub**
This implements what was discussed in #3.

### CODE REVIEW

**Review by peterstangl — CHANGES_REQUESTED** [review]
>> If loading fails, I would issue a warning, skip `make_measurement` and set a variable `sm_cov_loaded=False`. All methods that use the covariances should check if `sm_cov_loaded==True` and throw an error otherwise.
>
>Actually I think we don't have to do this since what will happen is that the first `FastLikelihood` instance will throw the `ValueError` "You need to call `make_measurement` first." which is exactly what the user should do. This way we don't have to add `try ... except` at several places in `GlobalLikelihood`.

_Originally posted by @DavidMStraub in https://github.com/smelli/smelli/issues/3#issuecomment-467459088_

This seems to be not the case for all methods. While `log_likelihood_sm` does exactly what you wrote above, `gl.obstable_sm` throws the error
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-a23372b819df> in <module>()
----> 1 gl.obstable_sm

~/Repositories/smelli/smelli/classes.py in obstable_sm(self)
    219                     info[obs]['name'] = obs if isinstance(obs, str) else obs[0]
    220                     info[obs]['th. unc.'] = np.sqrt(sm_cov[i, i])
--> 221                     info[obs]['experiment'] = m.get_central(obs)
    222                     info[obs]['exp. unc.'] = np.sqrt(exp_cov[i, i])
    223                     info[obs]['exp. PDF'] = NormalDistribution(m.get_central(obs), np.sqrt(exp_cov[i, i]))

AttributeError: 'NoneType' object has no attribute 'get_central'
```
I think this should yield a more clear error message.

And most importantly, `parameter_point` doesn't throw an error at all. There will only be an error when one goes on and tries to compute a log_likelihood using the `parameter_point` instance. I think this could be confusing for the user and an error should already be raised when one tries to instantiate the `parameter_point`.

**Comment by DavidMStraub** [comment]
OK, I believe this should be implemented now.

**Comment by peterstangl** [comment]
@DavidMStraub, I copied the docstring from flavio into the `make_measurement` method. I think it can be used as it is. Or do you think we should adjust something?

**Comment by DavidMStraub** [comment]
No, very good :+1:

**Comment by DavidMStraub** [comment]
Merge?

**Pull request merged**
